# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# You can specify a custom docker image from Docker Hub as your build environment.

image: python:3.6.2

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - python --version
          # Install runtime  and install dependencies
          - pip install numpy scipy numba visvis
          - pip install flit          
          # Enable fake display so that we can create windows
          - "export DISPLAY=:99.0"
          - "sh -e /etc/init.d/xvfb start"
          - sleep 3 # give xvfb some time to start
          # Install pirt
          - export FLIT_ROOT_INSTALL=1
          - flit install
          # Import
          - python -c 'import pirt; print(pirt)'
          