# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# You can specify a custom docker image from Docker Hub as your build environment.

image: python:3.6.2

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - python --version
          - pip install flit
          - pip install numpy scipy numba
          - export FLIT_ROOT_INSTALL=1
          - flit install          
          - python -c 'import pirt; print(pirt)'
          