# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# You can specify a custom docker image from Docker Hub as your build environment.

image: python:3.6.2

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - python --version
          # Install runtime  and install dependencies
          - pip install numpy scipy numba visvis
          - pip install flit invoke
          # Test style
          - invoke test --style
          - exit 0  # arg, no opengl, so we cannot use visvis
          # Enable fake display so that we can create windows
          - Xvfb :99 -ac -screen 0 1280x720x16 -nolisten tcp &
          - xvfb=$!
          - export DISPLAY=:99.0
          - sleep 3 # give xvfb some time to start
          # Install pirt
          - export FLIT_ROOT_INSTALL=1
          - flit install
          # Import
          - python -c 'import pirt; print(pirt)'
